### ISSUE TITLE
Branch off stable5

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/nextcloud-vue#2907]
In order to still be able to maintain patch releases we should branch off a stable5 branch before the first breaking change and probably backport fixes in order. 

- Commit before the first breaking change (#2704) is f8be4097

Any objections on this @nextcloud/vuejs ? From my perspective it would still be worth backporting fixes if needed to be able to ship to stable server/app branches.

**Comment by juliushaertl** [comment]
Useful commands for getting the PRs:

```
git log f8be409..master --oneline | grep Merge | grep -v dependabot | grep -v translations
git log v5.3.1..f8be409 --oneline | grep Merge | grep -v dependabot | grep -v translations
```

**Comment by juliushaertl** [comment]
Also the milestone https://github.com/nextcloud/nextcloud-vue/milestone/77?closed=1 seems to be still used, even though we have no way to release such a patch release

**Comment by jotoeri** [comment]
> Useful commands for getting the PRs:

If the changelog for v6-alpha is properly done, then it should also be possible to use this list, including links already. :wink:

**Comment by raimund-schluessler** [comment]
The really save option would be to just branch off stable5 from the 5.3.1 release with https://github.com/nextcloud/nextcloud-vue/commit/71e8f2f67b9e35e17b36287e89a1e7dd2a67c596, but I guess the commit you mentioned above before #2704 was merged should also be ok.

**Comment by juliushaertl** [comment]
This is the changelog from the commit https://github.com/nextcloud/nextcloud-vue/commit/f8be40973a40e28447ba546c1491b27f453469ef 

As it includes enhancements I'd still pick it but bump to 5.4 then.

## Unreleased (2022-08-02)

#### :rocket: Enhancement
* [#2552](https://github.com/nextcloud/nextcloud-vue/pull/2552) Make emojis selectable by tab ([@skjnldsv](https://github.com/skjnldsv))
* [#2668](https://github.com/nextcloud/nextcloud-vue/pull/2668) Merge Dashboard components into repository ([@raimund-schluessler](https://github.com/raimund-schluessler))
* [#2654](https://github.com/nextcloud/nextcloud-vue/pull/2654) add handle keyboard focus for accessibility ([@vanpertsch](https://github.com/vanpertsch))
* [#2629](https://github.com/nextcloud/nextcloud-vue/pull/2629) small cleanup of small modal size ([@szaimen](https://github.com/szaimen))

#### :bug: Bug Fix
* [#2638](https://github.com/nextcloud/nextcloud-vue/pull/2638) Fix lifecycle hook name in Avatar ([@raimund-schluessler](https://github.com/raimund-schluessler))
* [#2628](https://github.com/nextcloud/nextcloud-vue/pull/2628) Fix styleguide serve ([@raimund-schluessler](https://github.com/raimund-schluessler))

**Comment by juliushaertl** [comment]
Branched off now, closed the 5.3.2 milestone and moved the PRs accordingly to 5.4 and 6.0. Maybe anyone can check their PRs from the remaining changelog to see if anything needs or should to get backported for a new 5.4 release:

#### :bug: Fixed bugs
* [ ] [#2878](https://github.com/nextcloud/nextcloud-vue/pull/2878) Fix single action validation ([@raimund-schluessler](https://github.com/raimund-schluessler))
* [ ] [#2877](https://github.com/nextcloud/nextcloud-vue/pull/2877) Bring back AppNavigationToggle tooltip ([@raimund-schluessler](https://github.com/raimund-schluessler))
* [ ] [#2895](https://github.com/nextcloud/nextcloud-vue/pull/2895) Fix issues with Multiselect component ([@nickvergessen](https://github.com/nickvergessen))
* [ ] [#2882](https://github.com/nextcloud/nextcloud-vue/pull/2882) Fix box shadow colour of "tertiary-on-primary" button ([@danxuliu](https://github.com/danxuliu))
* [ ] [#2871](https://github.com/nextcloud/nextcloud-vue/pull/2871) Add a button style for being used on primary like in the header ([@nickvergessen](https://github.com/nickvergessen))
* [ ] [#2865](https://github.com/nextcloud/nextcloud-vue/pull/2865) Make captions real headings for improved a11y ([@nickvergessen](https://github.com/nickvergessen))
* [ ] [#2855](https://github.com/nextcloud/nextcloud-vue/pull/2855) Fix invalid setting section IDs ([@nickvergessen](https://github.com/nickvergessen))
* [ ] [#2695](https://github.com/nextcloud/nextcloud-vue/pull/2695) Change Prev/next links to buttons ([@vanpertsch](https://github.com/vanpertsch))
* [ ] [#2845](https://github.com/nextcloud/nextcloud-vue/pull/2845) Add headline to sidebar sections to improve landmarks ([@nickvergessen](https://github.com/nickvergessen))
* [ ] [#2846](https://github.com/nextcloud/nextcloud-vue/pull/2846) Fix HTML validation of AppNavigationToggle ([@nickvergessen](https://github.com/nickvergessen))
* [ ] [#2840](https://github.com/nextcloud/nextcloud-vue/pull/2840) Fix invalid tabindex and role ([@nickvergessen](https://github.com/nickvergessen))
* [ ] [#2841](https://github.com/nextcloud/nextcloud-vue/pull/2841) Remove invalid test-attr ([@nickvergessen](https://github.com/nickvergessen))
* [ ] [#2833](https://github.com/nextcloud/nextcloud-vue/pull/2833) Fix vue material design icons HTML validation ([@nickvergessen](https://github.com/nickvergessen))
* [ ] [#1946](https://github.com/nextcloud/nextcloud-vue/pull/1946) Properly align appnavigationtoggle ([@marcoambrosini](https://github.com/marcoambrosini))
* [ ] [#2738](https://github.com/nextcloud/nextcloud-vue/pull/2738) Move close button within modal boundaries ([@marcoambrosini](https://github.com/marcoambrosini))
* [ ] [#2576](https://github.com/nextcloud/nextcloud-vue/pull/2576) Increase padding of ColorPicker ([@quentinguidee](https://github.com/quentinguidee))

**Comment by raimund-schluessler** [comment]
There is a stable5 branch now.
