### ISSUE TITLE
Regressions after vue datepicker update

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/nextcloud-vue#994]
https://github.com/nextcloud/nextcloud-vue/pull/861

We should really have this fixed before 19.
CC @georgehrke @juliushaertl 

- [ ] Icons not centered
  ![Capture d’écran_2020-04-06_15-18-02](https://user-images.githubusercontent.com/14975046/78562853-504e1a00-781a-11ea-813e-3628acb93089.png)
- [ ] Rows/Columns touching
  ![Kazam_screenshot_00001](https://user-images.githubusercontent.com/14975046/78562854-50e6b080-781a-11ea-83f2-5a78537ba0b5.png)
  ![Capture d’écran_2020-04-06_15-22-20](https://user-images.githubusercontent.com/14975046/78562923-707dd900-781a-11ea-9d45-4bee228bb52a.png)
- [ ] Weird week hovering effect
  ![Kazam_screenshot_00002](https://user-images.githubusercontent.com/14975046/78562855-517f4700-781a-11ea-9d58-8946f7262b63.png)
- [ ] Weird animation on init:
  ![Peek 06-04-2020 15-23](https://user-images.githubusercontent.com/14975046/78563050-a4f19500-781a-11ea-815b-ad02f931f7ea.gif)

**Comment by georgehrke** [comment]
I'm super busy with E2E stuff at the moment, not sure I will have time for it.

**Comment by skjnldsv** [comment]
I'll try to dive into this :)

**Comment by skjnldsv** [comment]
fix in #995

**Comment by raimund-schluessler** [comment]
May I add that the datepicker is cut-off on some resolutions, e.g. in Tasks and Calendar:

Tasks:
<img width="290" alt="Tasks" src="https://user-images.githubusercontent.com/2496460/78590831-c1a1c300-7842-11ea-90e9-6b9f0bfdd87c.png">

Calendar:
<img width="272" alt="Calendar" src="https://user-images.githubusercontent.com/2496460/78590840-c6667700-7842-11ea-9a00-2310ff2466b2.png">

If it doesn't happen to you, play a bit with the zoom, either zoom-in or -out.

Should I create a separate issue, or do you want to track it here?

**Comment by skjnldsv** [comment]
Your second screenshot i not this calendar, we lost the arrow, so it's an old version I guess?

**Comment by raimund-schluessler** [comment]
> Your second screenshot i not this calendar, we lost the arrow, so it's an old version I guess?

It’s the current version from the AppStore on 18.0.3.

**Comment by georgehrke** [comment]
> It’s the current version from the AppStore on 18.0.3.

2.0.2 is still using a nc-vue version, that was still 🚢ing version 2 of the datepicker.
Current master is using version 3.
